### ISSUE TITLE
use rolling checksums

### ISSUE THREAD

**Issue by khimaros** [tkellen/memorybox#1]
this would help with deduplication, reducing disk usage for large libraries

**Comment by khimaros** [comment]
a library for this is available at https://go4.org/rollsum

**Comment by khimaros** [comment]
if you are not familiar, you may also find https://github.com/bup/bup an interesting project

**Comment by tkellen** [comment]
Thanks for sharing! I want the files and metadata stored by this software to be directly consumable by other systems with as few barriers as possible. As a result, I have intentionally traded storage efficiency for simplicity. Files are stored as-is. Metadata is JSON. No special tools are needed to work with archives created by memorybox.

For more context, please see this section of the README:
https://github.com/tkellen/memorybox#drawbacks

**Comment by khimaros** [comment]
simplicity is a very reasonable philosophy. thank you for the explanation.
